# Generated by Django 5.0.6 on 2025-02-28 19:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "db_connect",
            "0004_annotation_completed_time_annotation_labelled_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
