# Generated by Django 5.0.6 on 2025-03-05 20:05

import django.core.validators
from django.db import migrations, models
    

class Migration(migrations.Migration):

    dependencies = [
        ("db_connect", "0005_alter_annotation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
