# Generated by Django 5.0.6 on 2025-03-06

from django.db import migrations

def add_rows_to_my_table(apps, schema_editor):
    # Get the model you want to add the row to
    MyModel = apps.get_model('db_connect', 'Settings')

    # Delete all existing rows
    MyModel.objects.all().delete()

    # Add new rows
    MyModel.objects.create(
        key='submit',
        value=100,
        description='percentage of annotations go to review and rest go to completed'
    )

    MyModel.objects.create(
        key='accept',
        value=50,
        description='percentage of annotations go to SuperQC and rest go to completed'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('db_connect', '0006_settings'),
    ]

    operations = [
        migrations.RunPython(add_rows_to_my_table),
    ]