# Generated by Django 5.0.6 on 2025-03-08 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_connect", "0007_add_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotation",
            options={
                "ordering": ["-inserted_time"],
                "verbose_name": "Annotation",
                "verbose_name_plural": "Annotations",
            },
        ),
        migrations.AlterModelOptions(
            name="settings",
            options={
                "ordering": ["key"],
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
            },
        ),
        migrations.AlterModelTable(
            name="annotation",
            table="annotations",
        ),
        migrations.AlterModelTable(
            name="settings",
            table="settings",
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "db_table": "batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="annotation",
            name="batch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db_connect.batch",
            ),
        ),
    ]
