# Generated by Django 5.1.6 on 2025-03-11 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_connect", "0008_alter_annotation_options_alter_settings_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Segregation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inserted_time", models.DateTimeField(auto_now_add=True)),
                ("history", models.JSONField(default=list)),
                ("labelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("segregated", "Segregated"),
                        ],
                        default="uploaded",
                        max_length=50,
                    ),
                ),
                ("s3_file_key", models.CharField(max_length=255)),
                (
                    "s3_segregated_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "assigned_to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "labelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seg_labelled_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Segregation",
                "verbose_name_plural": "Segregations",
                "db_table": "segregations",
                "ordering": ["-inserted_time"],
            },
        ),
    ]
