# Generated by Django 5.1.6 on 2025-03-12 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_connect", "0009_segregation"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Invoice Type",
                "verbose_name_plural": "Invoice Types",
                "db_table": "invoice_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceSubtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "invoice_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtypes",
                        to="db_connect.invoicetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Subtype",
                "verbose_name_plural": "Invoice Subtypes",
                "db_table": "invoice_subtypes",
                "ordering": ["name"],
                "unique_together": {("name", "invoice_type")},
            },
        ),
    ]
