# Generated by Django 5.1.6 on 2025-03-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_connect", "0010_invoicetype_invoicesubtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="segregation",
            name="invoice_subtype",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="segregation",
            name="invoice_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="segregation",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("in-progress", "In-progress"),
                    ("segregated", "Segregated"),
                ],
                default="uploaded",
                max_length=50,
            ),
        ),
    ]
