# Generated by Django 5.1.6 on 2025-03-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "db_connect",
            "0011_segregation_invoice_subtype_segregation_invoice_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="segregation",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("in-progress", "In-progress"),
                    ("segregated", "Segregated"),
                    ("skipped", "Skipped"),
                ],
                default="uploaded",
                max_length=50,
            ),
        ),
    ]
