# Generated by Django 5.2 on 2025-05-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="history",
            field=models.JSONField(
                default=list,
                help_text="List of history records, each containing a timestamp and an action.",
            ),
        ),
    ]
