# Generated by Django 4.2.24 on 2025-10-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_task_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "section_type",
                    models.CharField(
                        choices=[("general", "General"), ("table", "Table")],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("task_type", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "section_schema",
                "ordering": ["name"],
                "unique_together": {("name", "task_type")},
            },
        ),
        migrations.CreateModel(
            name="FieldSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="api.sectionschema",
                    ),
                ),
            ],
            options={
                "db_table": "field_schema",
                "ordering": ["name"],
                "unique_together": {("section", "name")},
            },
        ),
    ]
