# Generated by Django 4.2.28 on 2026-02-10 07:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sectionschema_fieldschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('invoice-annotation', 'Invoice Annotation'), ('object-detection', 'Object Detection'), ('document-classification', 'Document Classification'), ('image-segmentation', 'Image Segmentation'), ('text-translation', 'Text Translation')], max_length=50)),
                ('schema', models.JSONField(default=dict, help_text='Defines the structure of the annotation task, including sections and fields.')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sectionschema',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.DeleteModel(
            name='FieldSchema',
        ),
        migrations.DeleteModel(
            name='SectionSchema',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project'),
        ),
    ]
