# Generated by Django 4.2.28 on 2026-02-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_project_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task_type',
            field=models.CharField(choices=[('document-parsing', 'Document Parsing'), ('object-detection', 'Object Detection'), ('document-classification', 'Document Classification'), ('image-segmentation', 'Image Segmentation')], max_length=50),
        ),
    ]
