# Generated by Django 4.2.28 on 2026-02-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_project_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('labelled', 'Labelled')], default='uploaded', max_length=50),
        ),
    ]
