from django.urls import path
from .home_views import (
    get_annotations,
    upload_document,
    assign_annotation,
    smart_assign,
    get_smart_assign_data,
    get_annotations_count,
    get_groups_with_users,
    dashboard_view,
    pre_label,
    get_batches,
    create_batch,
    delete_annotations,
)
from .seg_views import (
    get_segregations,
    upload_document_seg,
    assign_segregation,
    smart_assign_seg,
    get_smart_assign_data_seg,
    get_segregated_count,
    get_groups_with_users_seg,
    get_document_seg,
    get_next_seg,
    get_prev_seg,
    submit_segregated_s3,
    get_invoice_types,
    put_invoice_types,
    delete_segregations,
    skip_segregation,
)
from .triage_views import (
    get_document,
    get_json,
    save,
    accept,
    submit,
    move_to_completed,
    get_ocr_text,
    reject,
    get_next,
    get_prev,
)
from .settings_views import get_settings, update_settings

urlpatterns = [
    path(
        "get_annotations/<str:assignee>/<str:status>/<int:perPage>/<int:page>/<str:searchID>/<str:batch>/",
        get_annotations,
        name="get annotations",
    ),
    path("get_document/<str:id>", get_document, name="get document"),
    path("upload_document/", upload_document, name="upload document"),
    path("get_json/<str:status>/<str:id>/", get_json, name="get json"),
    path("assign_annotation", assign_annotation, name="assign annotation"),
    path("save/<str:status>/<str:id>/", save, name="save json"),
    path("accept/<str:status>/<str:id>/", accept, name="accept annotation"),
    path("submit/<str:status>/<str:id>/", submit, name="submit annotation"),
    path("reject/<str:status>/<str:id>/", reject, name="reject annotation"),
    path(
        "move_to_completed/<str:status>/<str:id>/",
        move_to_completed,
        name="move to completed",
    ),
    path("get_ocr_text/", get_ocr_text, name="get ocr text"),
    path("get_next/<str:id>/", get_next, name="get next"),
    path("get_prev/<str:id>/", get_prev, name="get prev"),
    path("smart_assign/", smart_assign, name="smart assign"),
    path("get_smart_assign_data/", get_smart_assign_data, name="get_user_groups"),
    path("get_annotations_count/", get_annotations_count, name="get_annotations_count"),
    path("get_groups_with_users/", get_groups_with_users, name="get_groups_with_users"),
    path("dashboard_view/", dashboard_view, name="dashboard_view"),
    path("pre_label/", pre_label, name="pre_label"),
    path("get_settings/", get_settings, name="get_settings"),
    path("update_settings/", update_settings, name="update_settings"),
    path("get_batches/", get_batches, name="get_batches"),
    path("create_batch/", create_batch, name="create_batch"),
    path("delete_annotations/", delete_annotations, name="delete_annotations"),
    # Segregation URLs
    path(
        "get_segregations/<str:assignee>/<str:status>/<int:perPage>/<int:page>/<str:searchID>/",
        get_segregations,
        name="get_segregations",
    ),
    path("upload_document_seg/", upload_document_seg, name="upload_document_seg"),
    path("assign_segregation/", assign_segregation, name="assign_segregation"),
    path("smart_assign_seg/", smart_assign_seg, name="smart_assign_seg"),
    path(
        "get_smart_assign_data_seg/",
        get_smart_assign_data_seg,
        name="get_smart_assign_data_seg",
    ),
    path("get_segregated_count/", get_segregated_count, name="get_segregated_count"),
    path(
        "get_groups_with_users_seg/",
        get_groups_with_users_seg,
        name="get_groups_with_users_seg",
    ),
    path("get_document_seg/<str:id>/", get_document_seg, name="get_document_seg"),
    path("get_next_seg/<str:id>/", get_next_seg, name="get_next_seg"),
    path("get_prev_seg/<str:id>/", get_prev_seg, name="get_prev_seg"),
    path(
        "submit_segregated_s3/",
        submit_segregated_s3,
        name="submit_segregated_s3",
    ),
    path("get_invoice_types/", get_invoice_types, name="get_invoice_types"),
    path("put_invoice_types/", put_invoice_types, name="put_invoice_types"),
    path("delete_segregations/", delete_segregations, name="delete_segregations"),
    path("skip_segregation/", skip_segregation, name="skip_segregation"),
]
